# ===== PACKAGE =====
[package]
name = "rayna_ui"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

# ===== DEPENDENCIES =====

[dependencies]

# Raytracing deps
rayna_core = {path = "../rayna_core"}
rayna_ui_base = {path = "../rayna_ui_base"}

# Display/UI
egui = "0.*"

# Maths
glam = { workspace = true }
glamour = { workspace = true }
num-traits = { workspace = true }

# Error handling
anyhow = { workspace = true }
thiserror = { workspace = true }

# Logging is amazing
tracing = { workspace = true }
tracing-subscriber = "0.3.18"

# Ray tracing
image = { workspace = true }

# Other
nonzero = { workspace = true }
flume = { version = "0.11.0", features = ["async"] }
itertools = { workspace = true }
valuable = { workspace = true }

# ===== FEATURES =====

[features]
default = [
    "backend_eframe",
    "backend_miniquad"
]

backend_eframe = ["rayna_ui_base/backend_eframe"]
backend_miniquad = ["rayna_ui_base/backend_miniquad"]