# ===== PACKAGE =====
[package]
name = "rayna_ui"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

# ===== DEPENDENCIES =====

[dependencies]

# Raytracing deps
rayna_core = {path = "../rayna_core"}
rayna_ui_base = {path = "../rayna_ui_base"}

# Display/UI
egui = "0.*"

# Maths
glam = {version = "0.*"}
glamour = {version = "0.*"}

# Error handling
anyhow = { version = "1.0.75", features = [] }

# Other

nonzero = "0.2.0"

# ===== FEATURES =====

[features]
default = [
    "backend_eframe",
    "backend_miniquad"
]

backend_eframe = ["rayna_ui_base/backend_eframe"]
backend_miniquad = ["rayna_ui_base/backend_miniquad"]