# ===== PACKAGE =====
[package]
name = "rayna_ui"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

# ===== DEPENDENCIES =====

[dependencies]

# Raytracing deps
rayna_core = {path = "../rayna_core"}

# Display/UI
egui = "0.24.1"
eframe = { version = "0.24.1", features=["glow", "default_fonts"] }

# ===== BUILD PROFILES =====
