# ===== PACKAGE =====
[package]
name = "rayna_ui"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

# ===== DEPENDENCIES =====

[dependencies]

# Raytracing deps
rayna_core = {path = "../rayna_core"}
rayna_ui_base = {path = "../rayna_ui_base"}

# Display/UI
egui = "0.*"

# Maths
glam = "0.*"
glamour = "0.*"

# Error handling
anyhow = "1.*"

# Other
nonzero = "0.*"
image = "0.*"
num-traits = "0.2.17"
flume = { version = "0.11.0", features = ["async"] }

# ===== FEATURES =====

[features]
default = [
    "backend_eframe",
    "backend_miniquad"
]

backend_eframe = ["rayna_ui_base/backend_eframe"]
backend_miniquad = ["rayna_ui_base/backend_miniquad"]