# ===== WORKSPACE =====
[workspace]
resolver = "2"
members = [
    "rayna_core",
    "rayna_ui",
    "rayna_ui_base",
]

[workspace.dependencies]
tracing = { version = "0.1.40", features = [] }

[profile.dev]
debug = 2