# ===== PACKAGE =====
[package]
name = "rayna_bin"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

# ===== DEPENDENCIES =====

[dependencies]

# Raytracing deps
#rtbvh = "0.6.2"

# ===== BUILD PROFILES =====
