# ===== PACKAGE =====
[package]
name = "rayna_engine"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

# ===== DEPENDENCIES =====

[dependencies]

rayna_shared = { path = "../rayna_shared" }


# Maths
glam = { workspace = true }
glamour = { workspace = true }
num-traits = { workspace = true }

# Raytracing
rtbvh = "0.6.2" # Used for accelerating intersection checks
image = { workspace = true }

# Logs
tracing = { workspace = true }

# Other
cfg-if = { workspace = true }
anyhow = { workspace = true }
thiserror = { workspace = true }
nonzero = { workspace = true }
dyn-clone = "1.0.16"
valuable = { workspace = true }
serde = { workspace = true }
memoize = { workspace = true }
itertools = { workspace = true }
derivative = { workspace = true}

# Perf
puffin = { workspace = true }
rayon = { workspace = true }
