# ===== PACKAGE =====
[package]
name = "rayna_ui_base"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

# ===== DEPENDENCIES =====

[dependencies]

egui = "0.24.1"
eframe = { version = "0.24.1", features=["glow", "wayland", "x11", "default_fonts"], optional = true }
egui-miniquad = { version = "0.14.0", features = [], optional = true }
miniquad = { version = "0.3.16", features = [], optional = true }

# Error handling
anyhow = { version = "1.0.75", features = [] }

# ===== FEATURES =====

[features]
default = ["backend_eframe"]

backend_eframe = ["dep:eframe"]
backend_miniquad = ["dep:egui-miniquad", "dep:miniquad"]
